### ISSUE TITLE
Widows Defender Alert

### ISSUE THREAD

**Issue by darzu84** [M0r0cc4nGh0st/LinkedIn-Learning-Downloader#5]
The windows antivirus keeps reporting me issue for the application and closes it forefuly. 

![image](https://github.com/user-attachments/assets/3f918654-7f70-42f0-bbd8-258baf5b6f62)

**Comment by darzu84** [comment]
And also this

![image](https://github.com/user-attachments/assets/c7bddaf7-15bc-44fa-a8ac-a07228269b94)

**Comment by M0r0cc4nGh0st** [comment]
Hello, my friend!

It's completely normal for Windows Defender or any other antivirus software to block the execution of this tool. This happens because I didn't use a valid certificate recognized by Windows. The tool was compiled simply, using open-source tools, with a self-signed (fake) certificate.

Regarding the temporary path: it is where the music file gets downloaded when you enable the background music feature. Once you disable the feature, the file is automatically deleted.

It's understandable that antivirus software or Windows Defender may find this behavior unusual, but I assure you the tool is safe. I take full responsibility for it, and it's intended solely for educational purposes to help users download LinkedIn Learning courses.

Thank you for your understanding!

**Comment by darzu84** [comment]
I added as exclusion in windows defender rule.

**Comment by M0r0cc4nGh0st** [comment]
Great to hear that! If there's any issue with the tool, please let me know, and I'll address it as soon as possible.
